### ISSUE TITLE
"Sign in to confirm you’re not a bot." error with YouTube videos

### ISSUE THREAD

**Issue by MichailiK** [jagrosh/MusicBot#1588]
### Bug Description

Playing YouTube videos may fail with the error "Sign in to confirm you’re not a bot."

YouTube seems to have recently rolled out this measure & is affecting all third party players/clients/downloaders. There's currently no known workaround.

### Steps to Reproduce

N/A

### Expected Result

N/A

### Debug Output

N/A

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by TheBjoel2** [comment]
downloading youtube videos through tor might be a workaround for this problem. just tested this, it works
```
$ torsocks yt-dlp https://youtu.be/AL5vANu2gok                                                                                                                                                               
[youtube] Extracting URL: https://youtu.be/AL5vANu2gok
[youtube] AL5vANu2gok: Downloading webpage
[youtube] AL5vANu2gok: Downloading ios player API JSON
[youtube] AL5vANu2gok: Downloading player 4fc7f9fa
[youtube] AL5vANu2gok: Downloading m3u8 information
[info] AL5vANu2gok: Downloading 1 format(s): 302+251
[download] Destination: Black Holes Explained For Gen-Z [AL5vANu2gok].f302.webm
[download] 100% of   48.22MiB in 00:03:40 at 223.78KiB/s
[download] Destination: Black Holes Explained For Gen-Z [AL5vANu2gok].f251.webm
[download] 100% of   10.01MiB in 00:00:49 at 207.41KiB/s
[Merger] Merging formats into "Black Holes Explained For Gen-Z [AL5vANu2gok].webm"
Deleting original file Black Holes Explained For Gen-Z [AL5vANu2gok].f302.webm (pass -k to keep)
Deleting original file Black Holes Explained For Gen-Z [AL5vANu2gok].f251.webm (pass -k to keep)
```

**Comment by Lancelot1151** [comment]
Same problem.

**Comment by cmorley191** [comment]
This repo fixed the issue by adding support for Oauth2, essentially allowing people to create dummy accounts for the bots to log in with: https://github.com/imputnet/cobalt/issues/551

Is this something we'd have to request support for in lavaplayer? Or is MusicBot responsible for querying the youtube API?

**Comment by Ozak93** [comment]
I'm facing the same issue:

`
Jun 17 23:49:14  env[441177]: [23:49:14] [ERROR] [AudioHandler]: Track BJhF0L7pfo8 has failed to play
Jun 17 23:49:14 env[441177]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Sign in to confirm you’re not a bot
Jun 17 23:49:14 env[441177]:         at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:72)
Jun 17 23:49:14 env[441177]:         at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98)
Jun 17 23:49:14 env[441177]:         at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35)
Jun 17 23:49:14 env[441177]:         at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:175)
`

**Comment by Moonchild6279** [comment]
I can confirm that with my VPS Server, it logs a "Sign in to confirm you’re not a bot." error everytime I want to play a youtube video on my server.

HOWEVER, just recently I found out my old instance of my bot in my local machine work perfectly with youtube.
Perhaps it's something to do with how the I.P of my local machine is tied to my youtube account perhaps? maybe youtube blocked requests from my server because of that.

**Comment by TheBjoel2** [comment]
ip.

пн, 24 июн. 2024 г., 09:44 Moonchild6279 ***@***.***>:

**Comment by Derahex** [comment]
a bot called "Nero Bot" manages to still play YT videos- would be worth looking into how they manage past the whole thing with their "nodes".

**Comment by TheBjoel2** [comment]
> a bot called "Nero Bot" manages to still play YT videos- would be worth looking into how they manage past the whole thing with their "nodes".

1) Nero Bot is not open source
2) Minerea is also able to play YT. Not open source
3) Chances are they are paying for a YT API or idk

**Comment by MichailiK** [comment]
> Some people over lavaplayer suggests to use [lavaplayer-fork](https://github.com/Walkyst/lavaplayer-fork) to solve youtube issues

We're already using [lavalink's lavaplayer fork](https://github.com/lavalink-devs/lavaplayer), which is still receiving maintenance. For this issue specifically, a simple update is very unlikely to fix anything, because this block also affects all of YouTube's own apps/clients.

**Comment by samusaran** [comment]
So I guess this is a problem to any bot playing from YouTube as a source, right?

**Comment by MichailiK** [comment]
See [the various](https://github.com/yt-dlp/yt-dlp/issues/10128) [other issues](https://github.com/TeamNewPipe/NewPipe/issues/11139) [on the internet](https://github.com/imputnet/cobalt/issues/5510) on this topic for a rough history of this. The cobalt.tools developers seem to have found a workaround related to OAuth2, however this has not been implemented in any lavaplayer fork yet, and also seems a bit risky.

**Comment by samusaran** [comment]
The issue is fixed for me on version 0.4.2 🎉

**Comment by MichailiK** [comment]
As this is an issue that affects every project using YouTube, several communities have come across a few discoveries. Here's a summary of what I've seen:

1. This is an IP block.
2. Instead of just banning one IP, it looks YouTube is blocking whole ASNs/IP ranges. If you encounter this issue, it's likely a "neighboring" IP address was bombarding YouTube, causing them to block the ASN/IP range you're in.
3. The [cobalt.tools developers seem to have found a workaround](https://github.com/imputnet/cobalt/issues/551) using OAuth2. This is currently not implemented in lavaplayer (the library we use to fetch & play tracks) and also seems a bit risky.
4. IPv6 rotation might also work, which lavaplayer supports & encourages using. We haven't put much thought about supporting IPv6 rotation on JMusicBot yet though.

In my opinion, I see two main ways JMusicBot could move forward:

1. Allow configuring IPv6 rotation for users on VPS' as they are most commonly affected by these blocks.
2. Implement support for an external tool (cobalt.tools) as a source, which have circumvented this block. I'm not sure if they would appreciate the additional traffic from JMusicBot users though.

Only my two cents though, neither are under consideration for now.

**Comment by T-h-o-r-p-e** [comment]
This same issue has started occurring for me, has an easy solution been found yet? (one that a novice like me could implement)

**Comment by MichailiK** [comment]
There is no solution at the moment.

**Comment by Snaacky** [comment]
This started affecting me on a Hetzner IP range yesterday. Not a solution per se, but managed to temporarily workaround it by routing my jmusicbot Docker container through my WireGuard docker container running a config from a paid VPN service.

**Comment by T-h-o-r-p-e** [comment]
> This started affecting me on a Hetzner IP range yesterday
I'm also using Hetzner. Not sure if that's a coincidence or not.

**Comment by MichailiK** [comment]
> I'm also using Hetzner. Not sure if that's a coincidence or not.

This is expected. As I mentioned earlier, it seems like YouTube is banning entire ASNs/IP ranges. Chances are pretty high that all of Hetzner’s ASNs/IPs have been banned.

**Comment by Ruok2bu** [comment]
As a test, on my server computer i created a new google account (so it appears that the registration is occurring from the banned ip) and logged in. I was able to play youtube video's in the browser! But when i log out in browser, once again im presented with the error. So if the bot can log into youtube, that should solve the problem for everyone.

**Comment by tag27** [comment]
> So if the bot can log into youtube, that should solve the problem for everyone.

No, apparently this block affects both with or without an account, on the same IP.
See: https://github.com/lighttube-org/LightTube/issues/154

**Comment by mersal-developing** [comment]
this also affects me 
i used netrc file and add the credentials of youtube but still get the same error

**Comment by ROBERT-MCDOWELL** [comment]
YT seems to want to shoot a bullet in his own foot.... I have the same issue from 4 servers in 4 different DC. well done YT, soon you are going to ban yourself as some of your servers are hosted in the same DC of ours!

**Comment by BenCos17** [comment]
can confirm it's happening for me on hetzner also      
not using musicbot though

**Comment by samusaran** [comment]
It’s also happening to me on Aruba (Italian hosting provider)

**Comment by xFanexx** [comment]
Same. Not working for me either. Using a Hetzner Dedicated Server with Windows Server 2022 // Docker Desktop.

**Comment by hydrogenicMetallium** [comment]
i am just popping in to say that after a bunch of tinkering with my OVHcloud server yesterday i only found out that if you run jmusicbot and then a VPN (OpenVPN + Windscribe is what ive used) on top of it then will the bot finally be able to play youtube links without any issues, granted this is still a workaround and you may have to restart your vpn again each time if youtube happens to ban the one the vpn is running on but so far ive had 0 issues since ive went and used this solution.
just thought id let everyone know about this since ive seen a bunch of people still trying to figure out how to get their bot to play yt links so yeah i hope this helps

**Comment by Zawodowiec1532** [comment]
same on OVH server.. any resolution is planned?

**Comment by BlobIsBack** [comment]
> same on OVH server.. any resolution is planned?

Using cloudflare warp on my racknerd vps fixed the issue BUT i lost accès to ssh and now use vnc because I didn't set up cloudflare warp correctly and I'm too lazy to reinstall it, I reccomend you to search on google stuff like "can't accès ssh after installing cloudflare warp" and you will probably find something to not have the same issue as me

Sorry if my English is bad

**Comment by C0la149** [comment]
Hello! I also encountered the same problem. Has anyone found a solution to this problem? My server is from Hentzer. Located in Finland!
![изображение](https://github.com/user-attachments/assets/1ec497e6-44a3-415e-9065-cd0935a5a234)
![изображение](https://github.com/user-attachments/assets/0600d993-f226-4f12-b86a-a13561b66026)
Of course I have a nextcloud cloud. But maybe someone already knows the solution to this problem?

**Comment by tag27** [comment]
> But maybe someone already knows the solution to this problem?

No, it doesn't have a 100% effective solution so far. There are repositories with the same problem, and others have some pulls that can fix the problem, but many will fix it temporarily. 

The best thing to do is to wait.

**Comment by ROBERT-MCDOWELL** [comment]
well, why not to totally boycott the corpofascists?

**Comment by C0la149** [comment]
> > But maybe someone already knows the solution to this problem?
> 
> No, it doesn't have a 100% effective solution so far. There are repositories with the same problem, and others have some pulls that can fix the problem, but many will fix it temporarily.
> 
> The best thing to do is to wait.

Wait what? How long will the ban last? or until a complete solution comes out?

**Comment by Ruok2bu** [comment]
One thing that can work and its not ideal. But what if the bot downloads the mp4 video and then plays the audio through the bot? And optionally caches the downloaded video into a folder structure on the hard drive so it doesnt need to contact youtube servers again. I realize this method can bloat the hard disk with GB's of files, but if they are also converted from mp4 (m4v) to ogg (not mp3 because ogg offers better compression than mp3) then some disk space would be saved.

I realize this method wont unban everyone's IPs but at least it would allow us to get around the ban.

**Comment by DaniDipp** [comment]
@Ruok2bu There is no difference between downloading and streaming a video from YouTube's point of view. It won't get around the ban.

**Comment by Ruok2bu** [comment]
> @Ruok2bu There is no difference between downloading and streaming a video from YouTube's point of view. It won't get around the ban.

But at least adding that ability could let us schedule when the bot accepts songs to download (in other words it wont trigger the bans all the time). For example, allowing music requests for set time of the day or up to x amount per hour so youtube is less likely to block.

**Comment by MichailiK** [comment]
This is highly unlikely to fix anything in a VPS/cloud service context (which are the people who get affected by this block the most.) YouTube applies a ban to the whole ASN (IP range.) If only one bad actor within your "IP range" is misbehaving by downloading lots of videos in a short period, you will end up being affected ta no fault of your own.

**Comment by Ruok2bu** [comment]
Then there's only one way out of this. Some rich person needs to buy a ton of google stocks, get on the board and then use their veto power to change the rules.

**Comment by ROBERT-MCDOWELL** [comment]
@MichailiK 
well, imagin someone using yt-dlp in an airport which usually has an ip range, good luck to ban an entire airport!

**Comment by C0la149** [comment]
> @MichailiK well, imagine someone using yt-dlp in an airport which usually has an ip range, good luck to ban an entire airport without any consequences!

xD

**Comment by tag27** [comment]
> > > But maybe someone already knows the solution to this problem?
> > 
> > 
> > No, it doesn't have a 100% effective solution so far. There are repositories with the same problem, and others have some pulls that can fix the problem, but many will fix it temporarily.
> > The best thing to do is to wait.
> 
> Wait what? How long will the ban last? or until a complete solution comes out?

They also don't know how long this ban lasts, they say it's 72 hours or it's permanent. (https://github.com/yt-dlp/yt-dlp/issues/10128#issuecomment-2180723436)

**Comment by Zawodowiec1532** [comment]
The solution might be to just log in. I checked it on my VPS and when i logged in, it started to work.
yt-dlp allow to login via parameters: https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#authentication-options
So I think you need to implement option to provide credentials for yt-dlp

**Comment by trodrigues** [comment]
> This started affecting me on a Hetzner IP range yesterday. Not a solution per se, but managed to temporarily workaround it by routing my jmusicbot Docker container through my WireGuard Docker container running a config from a paid VPN service.

@Snaacky would you happen to have a bit of guidance on you set up jmusicbot to go through the VPN? Is it a container level configuration?

**Comment by Snaacky** [comment]
@trodrigues This is what I'm using:
```yaml
services:
  jmusicbot:
    container_name: jmusicbot
    image: bas0korver/jmusicbot:latest
    restart: unless-stopped
    network_mode: "container:wireguard"
    volumes:
     - ./config:/opt/jmusicbot/config
```

```yaml
services:
  wireguard:
    container_name: wireguard
    image: linuxserver/wireguard
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
```

**Comment by cmorley191** [comment]
The [lavaplayer oauth PR] we are (maybe) waiting on has been making progress.

@MichailiK You mentioned a couple times that you think the idea of having JMusicBot users logging in with oauth seems "a bit risky." Could you explain that? I don't understand what the risks are.

**Comment by MichailiK** [comment]
Google could figure out it is not a legitimate client playing back videos. As using JMusicBot technically violates YouTube's TOS, they could terminate your Google account. The OAuth2 PR also states at the end this should not be used on your main Google account.

(For clarity, the OAuth2 API that's being used here is unofficial & undocumented, it's only meant to be used by Smart TV manufactures.)

**Comment by Zawodowiec1532** [comment]
> Google could figure out it is not a legitimate client playing back videos. As using JMusicBot technically violates YouTube's TOS, they could terminate your Google account. The OAuth2 PR also states at the end this should not be used on your main Google account.
> 
> (For clarity, the OAuth2 API that's being used here is unofficial & undocumented, it's only meant to be used by (Smart) TV makers as far as I'm aware.)

You can make warning to dont use main account, just create new one :)

**Comment by Daniyalkhan55** [comment]
how to fix this bug   "Sign in to confirm you’re not a bot" while  using the distube-ytdl package

**Comment by z80sui** [comment]
mark

**Comment by mwessman** [comment]
So is there any solution or workaround for this yet?

**Comment by MichailiK** [comment]
The only workaround at the moment is to play music from a non-banned IP address. We're currently waiting for upstream to implement OAuth2 login & then consider adding it to JMusicBot.

**Comment by andy01745** [comment]
I am having the same problem. 
![image](https://github.com/user-attachments/assets/fc18038b-6616-4d28-b3fd-fa656ded09d1)

**Comment by Johannes11833** [comment]
You could also route the requets through [warp](https://github.com/cmj2002/warp-docker) for now. Seems to work most of the time and does not require a paid vpn service.

````yml
services:
  jmusicbot:
    image: ghcr.io/yojoshb/jmusicbot-docker
    container_name: jmusicbot
    # environment:
    #   - BOT_VERSION=0.3.9 # You can omit the environment variable if you just want to run the latest version
    volumes:
      - ./config:/config
    restart: unless-stopped
    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    image: caomingjun/warp
    restart: unless-stopped
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp

````

**Comment by alanman87** [comment]
> You could also route the requets through [warp](https://github.com/cmj2002/warp-docker) for now. Seems to work most of the time and does not require a paid vpn service.
> 
> ```yaml
> services:
>   jmusicbot:
>     image: ghcr.io/yojoshb/jmusicbot-docker
>     container_name: jmusicbot
>     # environment:
>     #   - BOT_VERSION=0.3.9 # You can omit the environment variable if you just want to run the latest version
>     volumes:
>       - ./config:/config
>     restart: unless-stopped
>     network_mode: "service:warp"
>     depends_on:
>       - warp
>   warp:
>     image: caomingjun/warp
>     restart: unless-stopped
>     ports:
>       - '1080:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./data:/var/lib/cloudflare-warp
> ```

How would we do this for pterodactyl? I am running the bot via the pterodactyl egg.

**Comment by judeabc20221** [comment]
> You could also route the requets through [warp](https://github.com/cmj2002/warp-docker) for now. Seems to work most of the time and does not require a paid vpn service.
> 
> ```yaml
> services:
>   jmusicbot:
>     image: ghcr.io/yojoshb/jmusicbot-docker
>     container_name: jmusicbot
>     # environment:
>     #   - BOT_VERSION=0.3.9 # You can omit the environment variable if you just want to run the latest version
>     volumes:
>       - ./config:/config
>     restart: unless-stopped
>     network_mode: "service:warp"
>     depends_on:
>       - warp
>   warp:
>     image: caomingjun/warp
>     restart: unless-stopped
>     ports:
>       - '1080:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./data:/var/lib/cloudflare-warp
> ```

Thanks, it's work!

**Comment by Harshraj9812** [comment]
> [!NOTE]
> Wrap Workaround is only working on `jmusicbot:0.4.3` Release version only. 


**Tested & Working `docker-compose.yaml`**
**Add your - `BOT TOKEN`**
```yaml
version: "3"
services:
  discord-bot:
    container_name: Hr-Music-bot-Discord
    restart: unless-stopped
    image: harshraj9812/hr-bot-jmusicbot:0.4.3
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
    # BOT TOKEN
      - TOKEN=
    network_mode: "service:warp"
    depends_on:
      - warp
  warp:
    container_name: Wrap-Hr-Music-bot-Discord
    image: caomingjun/warp
    restart: unless-stopped
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp

```

**Comment by driftywinds** [comment]
> ```yaml
> version: "3"
> services:
>   discord-bot:
>     container_name: Hr-Music-bot-Discord
>     restart: unless-stopped
>     image: harshraj9812/hr-bot-jmusicbot:0.4.3
>     labels:
>       - "com.centurylinklabs.watchtower.enable=false"
>     environment:
>     # BOT TOKEN
>       - TOKEN=
>     network_mode: "service:warp"
>     depends_on:
>       - warp
>   warp:
>     container_name: Wrap-Hr-Music-bot-Discord
>     image: caomingjun/warp
>     restart: unless-stopped
>     ports:
>       - '1080:1080'
>     environment:
>       - WARP_SLEEP=2
>       # - WARP_LICENSE_KEY= # optional
>     cap_add:
>       - NET_ADMIN
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=0
>       - net.ipv4.conf.all.src_valid_mark=1
>     volumes:
>       - ./data:/var/lib/cloudflare-warp
> ```

Can you build an arm64 image, or teach me how to do it for myself? Thank you so much!
EDIT: - Nevermind, I ended up using this: - https://github.com/jagrosh/MusicBot/issues/1588#issuecomment-2295305229, which has arm64 support and it worked!

**Comment by MichailiK** [comment]
The upstream project [has recently implemented OAuth2 authentication](https://github.com/lavalink-devs/youtube-source/releases/tag/1.7.0). I've just gotten around to write an implementation for it in #1670. I expect for this to be part of JMusicBot 0.4.5, to be released soon.

It should be trivial to set up, but I'll comment with quick instructions once 0.4.5 releases.

**Comment by ghost** [comment]
The west is collapsing

**Comment by zaughon** [comment]
The bot i'm running was recently hit by this issue. The thing is, the bot hadn't played any music for weeks, which made me wonder, is the bot constantly connecting to YT even when not playing music? If yes, what is the reasoning behind this? 
Or is it lavalink doing that for unknown reasons?

**Comment by DaniDipp** [comment]
@zaughon 
No, it's not connecting to YouTube when not searching for or playing videos. The reason is that YouTube is banning whole IP ranges of data centers. It's not personal.

**Comment by Abujaman4685454** [comment]
![Screenshot_20240911-155957](https://github.com/user-attachments/assets/01e54bae-7bcd-4e58-b50b-d8db638eea83)

My inner tube was going fine until this came on telling me I should sign in to confirm that am not a bot I don't know and even though I restarted the app it's still happening 🥺😩

**Comment by Abujaman4685454** [comment]
![Screenshot_20240911-155957](https://github.com/user-attachments/assets/4f14a8fb-f15b-481c-88c6-521e67c7a01d)


My app was going well until this came and even though I try to restart the app it's still🥺🥺 please I need help

**Comment by MichailiK** [comment]
@Abujaman4685454 
> InnerTube

Note that you're posting this in the JMusicBot repository. You will need to ask help in the [InnerTube](https://github.com/tombulled/innertube) repository, not here.

**Comment by FOS92** [comment]
The IP Ban Is Real Had To Change My Hosting Location 3 times for the bot to work again

**Comment by RayPlays** [comment]
I used the jMusicBot for about half year, it worked really well and I love it, but after the last update it just don't want to play music from youtube at all because "Sign in to confirm you are not a bot" issue. Tried a lot of different discord music bots and found this:

https://github.com/LakhindarPal/discord-player-bot

Its a cool simple, easy to setup music bot, works both on windows and linux, and plays music from YouTube, Spotify, SoundCloud, Apple Music, Deezer, Tidal, and from more sources.
Since it is using OAuth2 you guys should go take a look on it, maybe it can be used somehow to make jMusicBot better

**Comment by tag27** [comment]
>  Since it is using OAuth2 you guys should go take a look on it, maybe it can be used somehow to make jMusicBot better

There's already a pull request from jMusicBot adding support for OAuth2, at least for YouTube (See #1670). You can test it if you want.

**Comment by redswgd** [comment]
i am facing the same issue.maybe open youtube in private window might solve the problem.

**Comment by MichailiK** [comment]
Thanks for all the thoughts & suggested workarounds everyone! We are now moving forward with implementing a way to login to an (**alternative/burner!!!**) Google account using OAuth2:

- #1670

As plenty of workarounds have been suggested here & this issue's comments have somewhat derailed into chatter (which is probably cluttering the notifications of those subscribed to this issue), I'm going to lock it for now.

Once account login has been implemented & released, I'll comment again with quick instructions on authorizing JMusicBot with your Google account.

**Comment by MichailiK** [comment]
Unfortunately, YouTube has begun to crack down on the OAuth2 workaround, so it won't be viable. For people on VPS' (which are the most affected by this issue) might be able to use their (/64 or larger) IPv6 address space to workaround the IP bans. I'll see if I can get that implemented in JMusicBot, hopefully some time in the near future.
